name: json_scheme_validator
description: A utility class to validate json records against a scheme. package has no dependency on other packages, uses plain dart code.
repository: https://github.com/adelelsayed/json_scheme_validator
version: 1.0.0

environment:
  sdk: ">=2.12.0"

dependencies:

dev_dependencies: